version: '2'
services:
  web:
    image: nginx
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.template
    volumes_from:
      - php
    ports:
      - "${NGINX_PORT}:80"
    environment:
      NGINX_ROOT: /var/www/html/www
      NGINX_PORT: "${NGINX_PORT}"
      NGINX_HOST: "${NGINX_HOST}"
    links:
      - php:php-fpm
    command: /bin/bash -c "envsubst '$$NGINX_ROOT $$NGINX_PORT $$NGINX_HOST' < /etc/nginx/conf.d/default.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
  php:
    build: .
    volumes:
      - /var/www/html/www
    links:
      - db
      - redis
    environment:
      ADMIN_EMAIL: "${ADMIN_EMAIL}"
      ADMIN_PASSWORD: "${ADMIN_PASSWORD}"
      WEB_HOST: "${NGINX_HOST}"
      DB_HOST: db
      DB_APP_NAME: "${DB_APP_NAME}"
      DB_DATA_NAME: "${DB_DATA_NAME}"
      DB_USER: "${DB_USER}"
      DB_PASSWORD: "${DB_PASSWORD}"
  db:
    image: mariadb
    ports:
      - "3306:3306"
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 1
      # user1:pass1@db1;user2:pass2@host2
      DATABASE_USER: "${DB_USER}"
      DATABASE_PASSWORD: "${DB_PASSWORD}"
      DATABASES: "${DB_APP_NAME},${DB_DATA_NAME}"
    volumes:
      - ./mariadb/initdb.d:/docker-entrypoint-initdb.d
  redis:
    image: redis:alpine